NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GD77TON2KSHBORKO6K3O332JNS5S53PVCZXHTQCSLGOYUUFHRES3ESH5"
]
VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME="StellarTrade"
ORG_URL="https://stellartrade.netlify.app/"
ORG_DESCRIPTION="We are proud members of the Digital Asset Trading Federation, a community dedicated to promoting the trading of highly profitable tokens. Our primary objective is to educate and inform individuals about the Stellar portal, empowering them to enhance their trading expertise and maximize their profits in the dynamic world of digital assets"
ORG_TWITTER="@_StellarTradeus"
ORG_LOGO="https://stellartrade.netlify.app/assets/img/x21p-FXc_400x400.jpg"
ORG_OFFICIAL_EMAIL="stellartradexlm@gmail.com"


[[CURRENCIES]]
code="xcb"
issuer="GAIMV36WSTXZTW22DAGKMO34N4CWTOC4CZCKEAUIEHT47DQ2VS5FHJLY"
anchor_asset="false"
name="Cobalt"
desc="Cobalt is an essential mineral used for batteries in electric cars, computers, and cell phones. Demand for cobalt is increasing as more electric cars are sold, particularly in Europe, where governments are encouraging the sales with generous environmental bonuses."
image="https://i.ibb.co/LvRv9fM/cobalt.png"
fixed_number=10000000
max_number=10000000
is_unlimited=false
#Cobalt was issued using the open and inclusive Stellar blockchain network.




